### ISSUE TITLE
Downloading contract information is not working.

### ISSUE THREAD

**Issue by romney68** [fedspendingtransparency/USASpending-Issue-Tracker#34] opened 2015-04-10 19:58 UTC
Attempting to download FY14 Defense contract data (csv).  Receive the message that this is will be a large file (which is understood) and will take time to download - estimate is 30-60 minutes.  However, request ran for almost 140 minutes before I closed my browser.  Report never generated.  Also tried to copy/paste the link provided into my browser (as the web page recommended) when I closed my browser after 140 minutes.  Received a 404 Not Found error, indicating no such key existed.  Need to be able to download large amounts of data like this.  This is common practice.

**Comment by kaitlin** [comment] 2015-04-10 20:27
Thanks for reporting @romney68! I think this is a duplicate of #31 . We believe that this is a caching issue. Can you try clearing your browser cache and trying again? (You can also use an incognito window in Chrome to disable caching).

Also, I happened to generate a file for DoD contracts in 2014 about 45 minutes ago. You should be able to use the same permalink as an interim solution:
http://download.usaspending.gov/datadownlods/Contracts/4d74d927/Data_Feed.csv

Since this is a duplicate of #31 I'm going to close this for now. If you're still experiencing issues, can you comment on that issue? Thanks!

**Closed by kaitlin** 2015-04-10 20:27 UTC
