### ISSUE TITLE
Data Downloads Behaving Inconsistently

### ISSUE THREAD

**Issue by kaitlin** [fedspendingtransparency/USASpending-Issue-Tracker#31] opened 2015-04-10 18:11 UTC
The Data Downloads page doesn't seem to be generating files, and intermittently reports that there are no records for parameters that would normally have records.

Right now, it's showing no FEMA grants for 2010:
![screen shot 2015-04-10 at 2 09 07 pm](https://cloud.githubusercontent.com/assets/75555/7093955/5daf25d6-df8b-11e4-9b42-4ccd83a0a966.png)

But sometimes it does show records, and just shows the "Generating" dialogue forever. I tried to download DoD contracts for FY 2011 this morning and it never created the file. Also, @michaelmcclellan reports that it never generated results for FEMA grants for 2010.

**Comment by michaelmcclellan** [comment] 2015-04-10 18:14
Thanks Kaitlin! Yes, I’ve also had the page display NO RECORDS at times too.


Michael O. McClellan
Program Analyst
Division of Financial Assistance Policy & Oversight (FAPO)
Office of the Chief Financial Officer (OCFO)
U.S. Department of Homeland Security (DHS)
Office: 202.447.5161
Mobile: 202.407.3513
Michael.Mcclellan@hq.dhs.gov

[cid:image001.gif@01CB9C38.C5817B50]

**Comment by kaitlin** [comment] 2015-04-10 18:50
It seems like this may be a caching issue. @michaelmcclellan can you try clearing your browser cache completely, and trying to download the FEMA grants data again? I was able to successfully download it in an incognito window in Chrome (a nice shortcut to avoiding any caching). I am still testing the DoD contracts download.

**Comment by Tiger74** [comment] 2015-04-10 19:51
How do I add an issue? I’m new to GitHub.

**Comment by bsweger** [comment] 2015-04-10 19:57
@Tiger74 there's a green button near the top right-hand corner of this page that says "new issue." Click that to open a new issue. Thanks!

**Comment by Tiger74** [comment] 2015-04-10 20:00
Could you please send me the link to the page that has the “ new issue” button? I’ve been on several different pages in GitHub and I haven’t seen that button on any of them.

**Comment by Tiger74** [comment] 2015-04-10 20:02
Never mind … I just found the green button.

**Comment by kaitlin** [comment] 2015-04-10 20:29
I can confirm that the download for all DoD contracts in FY 2014 worked for me. Here's a permalink in case anyone needs it:
http://download.usaspending.gov/datadownlods/Contracts/4d74d927/Data_Feed.csv

**Comment by michaelmcclellan** [comment] 2015-04-13 16:44
I just ran the report again for FEMA FY10 (without clearying my cache) and it seems to function properly at this time.

**Comment by mcpeate** [comment] 2015-04-13 17:28
@kaitlin Though the issue seems to be fixed at the agency level (after clearing my browser cache), I'm still having problems generating a file at the bureau level. Screenshot of DIA, though I tried several bureau-level searches for 2014 and all of them produced "0 records". Let me know if you'd like me to open a new issue.

![bureau-download-diafy14](https://cloud.githubusercontent.com/assets/4594518/7121208/de104c94-e1e0-11e4-82c0-e076fa0bfb73.png)

**Comment by bsweger** [comment] 2015-04-13 20:09
@mcpeate Thanks for your additional testing. I found some unexpected behavior re: duplicate bureau names when investigating this and logged it under #38.

I also want to make sure we capture anything else that's happening with bureau names. Can you confirm that DIA and the other bureaus you tested awarded contracts in FY 2014? I pulled a few DoD records from FPDS just to get a few bureaus that awarded contracts. Using those bureau names (e.g., Defense Health Agency, Dept of the Army) in a USASpending search returned records.

Appreciate you lending your DoD contract knowledge to this issue!

**Comment by mcpeate** [comment] 2015-04-13 21:33
@bsweger Thanks. You're right. Sorry- I assumed that DIA and the few others I searched on had records. I guess the problem I'm having now is your current list of options for DOD seems to be a mixture of contracting agency, funding agency, and potentially Major Command level. So, as an example, if I search for National Guard Bureau in the USAspending data download section which searches by contracting agency (I assume), there are no records. This corroborates with FPDS-NG. If I search for them by the funding agency in FPDS-NG, they have records but no dollars. However, if I search for NGB by Major command in FPDS-NG, I see $2.1B. I guess I'm wondering where you got your list of options from. I may need a lifeline here: @romney68.  If you only allow users to search by contracting agency in the bulk download section, then you should probably restrict it to the subset of contracting agencies that exist. Thoughts?

**Comment by bsweger** [comment] 2015-04-14 18:45
@mcpeate If I understand correctly, you're asking for clarity on what exactly is represented in USASpending's list of bureau names and also for that list to be limited to bureaus that actually have awards records?

If that's correct, I think it makes sense to open a new issue, since this one is related to the actual download behavior. Thanks again for your continued feedback!

**Comment by mcpeate** [comment] 2015-04-14 19:45
@bsweger Not exactly, though it still may be a separate issue. At present, your code to identify spend/actions for a particular entity labeled "bureau" at USAspending is only pulling at the department and agency level (in FPDS-NG), yet your drop-down choices are including Major command/sub command entities. National Guard Bureau, as an example, has contract spend, but it is listed in FPDS-NG as a 'Major Command' (under the contracting agency of Army) rather than as a stand-alone agency (or 'bureau' in USAspending terminology). So it is technically incorrect for USAspending to claim that NGB (and AMC, etc.) have no contract actions/spend. As stated earlier, I'm fine if this is a separate issue.

**Comment by bsweger** [comment] 2015-04-14 20:48
Thanks @mcpeate. I moved this conversation to #43 so we can make sure it's tracked appropriately.

**Comment by mcpeate** [comment] 2015-04-20 14:22
@bsweger I know we've closed this issue, but I have tried to download contracts for all agencies for FY14 (and other fiscal years) multiple times on many different computers (after clearing my browsing cache) and I get an error every single time. I NEVER had this problem with bulk downloads on the old site. I usually get something like "error generating the file. Please try again."

**Comment by kaitlin** [comment] 2015-04-20 14:38
I will reopen the issue @mcpeate. Can you let us know what browser(s) and version(s) you are using? Thanks!

**Comment by mcpeate** [comment] 2015-04-20 14:54
@kaitlin I'm using chrome, version 42.0.2311.90 m. I've also tried it in chrome's incognito browser.

**Comment by jhariani** [comment] 2015-04-20 15:43
I'm getting the same "error generating the file" error when I attempt to download large amounts of data. For example, these settings:

![screen shot 2015-04-20 at 11 41 08 am](https://cloud.githubusercontent.com/assets/688874/7233982/20839966-e752-11e4-8e31-a64e9f13868c.png)

...will eventually result in the "error generating the file" error. It does provide a link to download the file after "30-60" minutes (http://download.usaspending.gov/datadownlods/Contracts/199bd8fd/Data_Feed.csv), but I've been waiting for more than an hour and continue to get this error:

![screen shot 2015-04-20 at 11 42 12 am](https://cloud.githubusercontent.com/assets/688874/7234022/4ef4f7ea-e752-11e4-84a6-a8de40a30da2.png)

**Comment by bsweger** [comment] 2015-04-22 17:39
Adding some information reported by @JohnEFreeman in #45 so we can group all of the people reporting issues with large downloads together.

>Once I get to "Generating file..." with a URL, I can copy the URL of the dialog box to, say, Excel. Clicking gets a 404 error. 
Back at the dialog containing the "Generating file..." dialog, I expected to be able to close the dialog and click on the URL later, but that never worked.
So I left the "Generating file..." dialog open for many hours, and I finally got a "File generation is complete" message (or the equivalent). I assumed that the file was there, so I clicked on the URL, which switched me to a new tab whose heading reads "Waiting for download.usaspending.gov", with an activity indicator. It's been like that for 4 hours or more.

>More details on my Data Download requests: I requested using these parameters: Award type = prime, spending type = Contracts, Agency = All, Bureau = View All, Fiscal Year = 2015 ...2006 (each requested separately), Recipient State = All, Place of Performance State = All, Obligation Date, 
Start Date = 10/01/[xxxx], End Date = 09/30/[yyyy] where xxxx = FY -1 and yyyy = FY, File Type = CSV or TSV (tried both). I tried on Saturday, Sunday, and Monday, and once on Tuesday. Feedback of number of records appeared correct for each request. Sometimes I left off the End Date because of previously reported problems. Initially, I assumed that, once I had the URL, I could close the dialog and wait and click on the URL to retrieve the file. I did that successfully for FY2015 on Saturday, but have had no success since with other years.
I have also let the dialog stay open until I received the message "File generation is complete" after which I clicked on the URL, and this opened a new Tab with the heading "Waiting for download.usaspending.gov" with a spinning activity indicator. That page was blank, and it never came back with a result. (Never = at least 2 days). I've tried this using Windows 7, Windows 8.1, and with IE 11.0.9600.11728 and later, and Google Chrome version 42.0.2311.90 m.

**Comment by bsweger** [comment] 2015-04-22 17:40
I can confirm that requesting a large volume of data results in an error message:

![screen shot 2015-04-22 at 1 07 28 pm](https://cloud.githubusercontent.com/assets/540544/7281046/1c7eaaa0-e8f5-11e4-83e5-ae1855668011.png)

**Comment by bsweger** [comment] 2015-04-28 13:51
@mcpeate @jhariani @JohnEFreeman Just circling back to let you know that the team is still investigating the download issues you've reported. I also wanted to let you know that the team is also working to restore the full version of the bulk download files (see #4 for more information). Thanks again for your feedback.

**Comment by bsweger** [comment] 2015-05-04 21:12
This error was also reported today by @Umer08 (in #62). Just noting that here, since it seems that this issue is affecting numerous users.

**Comment by tacuba** [comment] 2015-05-05 17:16
I want to add that I'm also having consistent errors when trying to generate files.  I've made numerous attempts in both IE 10 and Chrome v42.  I gave up on trying to generate full Fiscal Year reports of contracts and instead attempted to generate FY reports based on Place of Performance.  I'm still having errors when reports are small in size (e.g., 60,000 transactions).  

![image](https://cloud.githubusercontent.com/assets/11951955/7478455/ed5ebea2-f328-11e4-911c-54a5c8c7b3e7.png)

**Comment by USAspendingalice** [comment] 2015-05-20 12:30
We believe the issues with the Data Download have been resolved so we're going to close this out in a few days.  If you are still experiencing issues, please let us know.  We appreciate all your feedback and your patience.

**Comment by USAspendingkevin** [comment] 2015-05-27 20:54
This issue is being closed since no one has reported it occurring in the last 22 days.

**Closed by USAspendingkevin** 2015-05-27 20:54 UTC
Labels: bug, confirmed, In Progress

**Comment by MarisaSchmader** [comment] 2015-05-28 02:02
I will be out of the office starting  05/22/2015 and will not return until
06/01/2015.

Please contact Joe Deem (304-480-5132) or Amanda Jackson (202-874-5146) in my
absence.

**Comment by Sprouls2** [comment] 2015-05-28 12:37
Before you close this item, do you have either your IT programmer or IV&V team (if you have on) try to replicate these errors and not rely only on reports from your customers to ensure the issue is resolved?  I believe trying to replicate issues is a “best practice” and is something you may be doing but this is not clear by this email.

Thanks,
Vince Sprouls
Information Management and Reporting Assistant Director
Financial Assistance Policy & Oversight
Office of the Chief Financial Officer
U.S. Department of Homeland Security
(202) 447-5075
