### ISSUE TITLE
Incorrect spending data for FY14 contract spend in DOD

### ISSUE THREAD

**Issue by mcpeate** [fedspendingtransparency/USASpending-Issue-Tracker#22] opened 2015-04-09 14:00 UTC
In the agency profile section for DOD's contract spend in FY14, contract spending displays $68B, when the DOD spent roughly $284B that fiscal year.
Sorry for not providing a screenshot earlier; I've attached one now:
![fy14-dodspend-incorrect](https://cloud.githubusercontent.com/assets/4594518/7073585/755adc80-dec2-11e4-9308-d2d0ad59bcb6.jpg)

**Comment by kaitlin** [comment] 2015-04-09 19:30
Thanks for reporting @mcpeate! We have confirmed the issue and are looking into it. I will post when we have an update.

**Comment by kaitlin** [comment] 2015-04-10 16:29
Ok, it looks like you were on the right track @mcpeate. The team has applied a fix, bringing the total up to $290B, but it looks like there's still a small discrepancy in the funding amount. Keeping the issue open for now.

**Comment by mcpeate** [comment] 2015-04-10 17:32
Sounds great. Just an fyi- I don't have a good sense of DOD's spend other than for contracts, but the contracts (by contracting agency) looks good. Re: funding agency, what agency codes are you referencing? My guess is you're probably missing a few obscure DoD-related funding agency codes.

**Comment by bsweger** [comment] 2015-04-13 16:02
In my testing, the fix for #26 corrects this issue as well. @mcpeate if you're satisfied with the resolution, I'll go ahead and close this.

One thing we clarified with the team is that the award totals on the agency profile page are different than the award totals on the map page because the latter includes only those awards that can be geocoded based on place of performance zip code.

**Comment by mcpeate** [comment] 2015-04-13 16:14
Ok, that works, @kaitlin. Thanks, you can close. Just a warning- I am focusing on things that are wrong first before moving to features I'd like added back in.

**Comment by bsweger** [comment] 2015-04-13 16:26
Thanks for confirming, @mcpeate. Much appreciated!

**Closed by bsweger** 2015-04-13 16:26 UTC
Labels: bug, confirmed, In Progress

**Comment by mcpeate** [comment] 2015-04-13 16:29
@bsweger sorry for not calling you out by username in the thread. My apologies!
