### ISSUE TITLE
Pie chart doesn't update

### ISSUE THREAD

**Issue by mcpeate** [fedspendingtransparency/USASpending-Issue-Tracker#25] opened 2015-04-09 17:55 UTC
The pie chart displaying an agency's type of spend (e.g., contracts, grants, etc.) permanently displays FY15 data regardless of which fiscal year one selects. The pie chart should display data for the fiscal year selected. 
Am adding a screenshot of the problem. I've selected FY14 DOD data but the pie chart is clearly displaying FY15 DOD data.
![screenshot-piechart-dodfy14](https://cloud.githubusercontent.com/assets/4594518/7073443/86dc7c44-dec1-11e4-9245-3d531c8ab00a.jpg)

**Comment by kaitlin** [comment] 2015-04-09 19:35
Thanks for reporting @mcpeate! I can confirm this issue and will report it to the team. I will report back when I have more information.

**Comment by kaitlin** [comment] 2015-04-10 17:41
Alright, the team has pushed a fix so that the pie chart updates correctly now. @mcpeate can you confirm? If so I'll close the issue.

**Comment by mcpeate** [comment] 2015-04-10 17:56
It looks like the initial problem is fixed @kaitlin. However, the number of transactions listed at the top under "total number of transactions" doesn't match the pie chart's total number of transactions. (I guess I assume those two should match as well.) It's not off by a lot, but it's still off. Should I open a new issue? FYI- it's hard to provide a screenshot since you won't see the number of transactions for both competed and non competed in a screenshot-ed pie chart, so unfortunately, it's won't be obvious without adding both competed/noncompeted actions and comparing it to the summary total number of transactions.

**Comment by bsweger** [comment] 2015-04-10 19:22
@mcpeate Thanks for taking the time to test the pie chart fix. I was able to recreate the issue you're reporting about the total number of transactions not matching the sum of the pie chart transactions.

Since you confirmed that the original pie chart issue is resolved, I'll close this issue. I opened #33 to capture the un-matched transaction numbers. Thanks!

**Closed by bsweger** 2015-04-10 19:22 UTC
Labels: bug, confirmed, In Progress
